import { Container, AppShell } from '@mantine/core';
import { type NextPage } from "next";
import Head from "next/head";
import Header from './components/Header'
import Hero from './components/Hero'
import Partner from "./components/Partner";
import About from './components/About';
import Register from './components/Register';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Hacklab Rock</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell>
        <Container mt={20} mx="auto" size="md" px="md">
          <Header />
          <Hero /> 
          <Partner />
          <About />
          <Register />
        </Container>
      </AppShell>
    </>
  );
};

export default Home;
